# Generated by Django 4.2.7 on 2023-12-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonafide_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_registration',
            name='Phone',
        ),
    ]
