# Generated by Django 4.2.7 on 2023-12-04 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bonafide_management', '0002_remove_student_registration_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_registration',
            old_name='Name',
            new_name='Password',
        ),
        migrations.RemoveField(
            model_name='student_registration',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='Application_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='UserName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Application_Status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (-1, 'Rejected')], default=0),
        ),
        migrations.AddField(
            model_name='student_registration',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
